### ISSUE TITLE
semistandard 6.0.0 compliance

### ISSUE THREAD

**Issue by Flet** [scenevr/server#68]
There are two new rules coming into `semistandard` 6.0.0:
* [no-extra-semi](http://eslint.org/docs/rules/no-extra-semi) - This rule is aimed at eliminating extra unnecessary semicolons. While not technically an error, extra semicolons can be a source of confusion when reading code.

* [semi-spacing](http://eslint.org/docs/rules/semi-spacing) - Disallow a space before semicolons and force a space after them.

We're linting this repository as part of the test suite, and we found two linting issues related to these new rules:

```
  lib/reflector.js:140:3: Unnecessary semicolon.
  test/reflector.js:16:1: Unnecessary semicolon.
```

Would you mind fixing these? If its less trouble I'd be happy to send a PR.

If you would like to try it out on the CLI, just run `npm install -g semistandard@next` to install 6.0.0. I'm holding off on making it `latest` for a little bit.

**Comment by bnolan** [comment]
Hey @Flet, thanks for making that change to semistandard, I think that's really sensible and those two semicolons were retarded, so that's great. :D
